"""empty message

Revision ID: 111409543ba1
Revises: f52b7007498c
Create Date: 2019-05-28 18:05:13.633577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111409543ba1'
down_revision = 'f52b7007498c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
