# instalando dependencias
RUN apt-get update && \
	apt-get -y install netcat && \
	apt-get clean

# establecer directorio de trabajo
WORKDIR /usr/src/app

# añadiendo e instalando requerimientos
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# agregando entripoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# añadiendo app
COPY . /usr/src/app

# ejecutar servidor
CMD ["/usr/src/app/entrypoint.sh"]
